
export const SET_MAP_REGION = 'SET_MAP_REGION';
export const SET_PLACE_DIRECTION = 'SET_PLACE_DIRECTION';
export const SET_PLACE_DESTINATION = 'SET_PLACE_DESTINATION';
export const SET_PLACE_ORIGIN = 'SET_PLACE_ORIGIN';